import{a as d,S as y,i as h}from"./assets/vendor-05a0208e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerpolicy&&(o.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?o.credentials="include":t.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function u(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const g="live_7zO2UtHss6WanH1oLQ1vnbzQS31rHHFk6zvi69lyordiqDagXpIxykJooBldDqh8";d.defaults.headers.common["x-api-key"]=g;function v(){return d.get("https://api.thecatapi.com/v1/breeds").then(e=>e.data)}function b(e){const r=`https://api.thecatapi.com/v1/images/search?breed_ids=${e}`;return d.get(r).then(s=>s.data)}const n=document.querySelector(".breed-select"),i=document.querySelector(".cat-info"),f=document.querySelector(".loader");let a;const p=new y({select:n});p.setData([]);n.classList.add("hidden");v().then(e=>{p.setData(e.map(r=>({text:r.name,value:r.id}))),m()}).catch(e=>{console.error("Error fetching cat breeds:",e),c("Oops! Something went wrong! Try reloading the page!")});n.addEventListener("change",function(){a=n.value,a&&(L(),b(a).then(e=>{if(e&&Array.isArray(e)&&e.length>0&&e[0].breeds&&e[0].breeds.length>0){const r=e[0].breeds[0];i.innerHTML=`
            <div class="cat-info-inner">
              <img src="${e[0].url}" alt="Cat Image" class="cat-image">
              <div class="cat-details">
                <h2>${r.name}</h2>
                <p class="description">${r.description}</p>
                <p><strong>Temperament:</strong> ${r.temperament}</p>
              </div>
            </div>
          `}else c("Oops! Unable to retrieve cat information. Please try again.")}).catch(e=>{console.error("Error fetching cat information:",e),c("Oops! Something went wrong! Try reloading the page!")}).finally(()=>{m()}))});function L(){f.style.display="inline-block",i.style.display="none",n.style.display="none"}function m(){f.style.display="none",i.style.display="flex",n.style.display="block"}function c(e){i.innerHTML="",f.style.display!=="none"&&h.error({title:"Error",message:e,position:"center",timeout:5e3})}
//# sourceMappingURL=commonHelpers.js.map
